# Generated by Django 3.1.6 on 2021-02-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_auto_20210217_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationobject',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.technician'),
        ),
    ]
